POST http://localhost:3003/payment-providers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ0MDAwMSwiZW1haWwiOiJzdXBlcmFkbWluQGdhdGVwYXkuZGV2IiwiaWF0IjoxNzY2NTUyMjA0LCJleHAiOjE3NjY1NTU4MDQsImF1ZCI6ImxvY2FsaG9zdDozMDAzIiwiaXNzIjoibG9jYWxob3N0OjMwMDMifQ.qC3pTba8r_NLfHDrI89yxow81M4IZ-SZGHABaPsLKJ8

{
  "name": "Gatepay Operations",
  "email": "operations@gatepay.dev",
  "status": "active",
  "expiryDate": "2026-12-31"
}