GET http://localhost:3003/payment/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdHVzZXIyQGdhdGVwYXkuZGV2IiwiaWF0IjoxNzY2NjQwODI4LCJleHAiOjE3NjY2NDQ0MjgsImF1ZCI6ImxvY2FsaG9zdDozMDAzIiwiaXNzIjoibG9jYWxob3N0OjMwMDMifQ.boW3VgrMNsEZWL9fYV8Y8sHUYNuphsUw3FKsCN1Erc0