GET http://localhost:3003/payment/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdHVzZXIyQGdhdGVwYXkuZGV2IiwiaWF0IjoxNzY2NjU1OTY0LCJleHAiOjE3NjY2NTk1NjQsImF1ZCI6ImxvY2FsaG9zdDozMDAzIiwiaXNzIjoibG9jYWxob3N0OjMwMDMifQ.JdTsFowOMrXhugV5_tEjeqsY5ryfjFCYgaBHgqCv5uc