GET http://localhost:3003/payment/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdHVzZXIyQGdhdGVwYXkuZGV2IiwiaWF0IjoxNzY2NDk2NDI5LCJleHAiOjE3NjY1MDAwMjksImF1ZCI6ImxvY2FsaG9zdDozMDAzIiwiaXNzIjoibG9jYWxob3N0OjMwMDMifQ.EaBR482-sVendmmPtUqRI3t02ODHfLHwtjfObGwBAPA