POST http://localhost:3003/users/username
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoidGVzdHVzZXIzQGdhdGVwYXkuZGV2IiwiaWF0IjoxNzY2NTU5NzUyLCJleHAiOjE3NjY1NjMzNTIsImF1ZCI6ImxvY2FsaG9zdDozMDAzIiwiaXNzIjoibG9jYWxob3N0OjMwMDMifQ.Id11w5IcdgGNVWwr90dEgZ9pgCPJyCDn_cl_C6i8ho4
Content-Type: application/json

{
  "username": "testuser3"
}