GET http://localhost:3003/users/test-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ0MDAwMSwiZW1haWwiOiJzdXBlcmFkbWluQGdhdGVwYXkuZGV2IiwiaWF0IjoxNzUyNjYzNjYzLCJleHAiOjE3NTI2NjcyNjMsImF1ZCI6ImxvY2FsaG9zdDozMDAzIiwiaXNzIjoibG9jYWxob3N0OjMwMDMifQ.39xsKz1XFYCUL4-fia9DH3xheDhq8ASLBgU1b6YocaU
