GET http://localhost:3003/auth/system-config
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ0MDAwMSwiZW1haWwiOiJzdXBlcmFkbWluQGdhdGVwYXkuZGV2IiwiaWF0IjoxNzUyNjcxOTg3LCJleHAiOjE3NTI2NzU1ODcsImF1ZCI6ImxvY2FsaG9zdDozMDAzIiwiaXNzIjoibG9jYWxob3N0OjMwMDMifQ.uDCkatOP0B8yIQHzyxNG4oRzDPVI3VOETRs-mW5_Cfk