POST http://localhost:3003/buyer/create-order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoidGVzdHVzZXIzQGdhdGVwYXkuZGV2IiwiaWF0IjoxNzY2NjM5MDE0LCJleHAiOjE3NjY2NDI2MTQsImF1ZCI6ImxvY2FsaG9zdDozMDAzIiwiaXNzIjoibG9jYWxob3N0OjMwMDMifQ.wo6wdEDW-a3e-awuMcbSj6kcSrwvyM8tuoEloF5nmOA
Content-Type: application/json

{
  "sellerUsername": "testuser2",
  "amount": "40.00",
  "productName": "Product G",
  "productDesc": ["phone", "watch"],
  "productCat": "electronics"
}