GET http://localhost:3003/outside/validate-token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOjE3LCJtZXJjaGFudElkIjoxLCJvcmRlcklkIjoiREkwMDAxMjAyNTA3MzAtMzYiLCJqdGkiOiI0NjQwZjJhN2JiNGM3NjVjYmMyZTU2YmZhODY5NTAzZCIsImlhdCI6MTc1NDMyNjA4OCwiZXhwIjoxNzU0MzI2Njg4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMyIsImlzcyI6ImxvY2FsaG9zdDozMDAzIn0.hYrOUaK2v1ZMFrGW9ztYVxZFT5qXb8Ait96ceM1_7x4
