GET http://localhost:3003/outside/status/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOjE2LCJtZXJjaGFudElkIjoxLCJvcmRlcklkIjoiREkwMDAxMjAyNTA3MzAtMzUiLCJqdGkiOiIyMjA3ODc5MDYzZjBkNDRkOTczNGQ2YTZmMWYwMTA1NyIsImlhdCI6MTc1NDMyNTEzNiwiZXhwIjoxNzU0MzI1NzM2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMyIsImlzcyI6ImxvY2FsaG9zdDozMDAzIn0.yBDHPdt3PCz4T70jsatQorCnGMCbCk_tFqFfnRjmO9g